# 조건 예시
conditions:
  - name: "상승_추세_돌파"
    description: "5일 이동평균선이 20일 이동평균선을 상향 돌파"
    rules:
      - type: "cross_over"
        indicator1: "MA_5"
        indicator2: "MA_20"
      - type: "volume_increase"
        threshold: 1.5  # 평균 거래량 대비 1.5배 이상

  - name: "과매도_반등"
    description: "RSI가 30 이하에서 반등"
    rules:
      - type: "indicator_threshold"
        indicator: "RSI"
        condition: "<="
        value: 30
      - type: "price_increase"
        days: 1
        threshold: 0.02  # 2% 이상 상승
